[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a649631a80822c3cc56dfdbb204273c6451ec36b"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "55625127a1af167ccdfa771b3b21eece2b2c9f2f2a5d062adf5784ab12118792"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.i686-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8688b3c6aafe910b1feebcbda158f198fd79d37e"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "33afcbf9f6d968f3093783aeb65bef7bc5f295ef5aa6e7d8a3c9479cad717943"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb4327c8705501af3cef228d799c67c98c2b6b22"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "c1ecd6dd4903f2aad8d099c165ccb3de7f6a468c3608313eb7607e124f673f45"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.aarch64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33c5463176f27da0d8f8d90d5690ca8f190411c7"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "a7ab7f884965da0220122a4a6eaf3e51c1bf028201d1e64973a43133d4720f06"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv6l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7230e8c3158eb8d2de5208448221625a43868572"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "6d18b7b15b2733404b42df2cdcabb66ba25c3ffb7173820ff1d0b9cbe2f8fd1c"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv7l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "428503bf7f0f2638592199ff99efad5fd55bdfbd"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "947ee8441e02004b160a62b0234cc5a08ebbd04949033b1a791701aa181ccb59"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.powerpc64le-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfe5cc46d5c9e86a9b181fc5757b38aa62af0587"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "7f5f6c45892ccd51edcb443ba8c7fa59fd24de121a235f1f2d23e87ac19a8ccb"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f99a59aa4428aad0b36aa4489556d7d1c9802d2"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "f9f3e43541d9d5fb4cabd6fe0848b5277232b15a3f881825c00a3d07f1416eb3"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.aarch64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2e5b8bcaac9e07d6c5ffa1d1ee899f0ed170cc1"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "81348249e7ff9bbe26f01a9020cd3825ad025cc8af880fd3974d6653e2fea028"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv6l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8ed82b9fef6f7cb04e7e5488e0b971f9f5c4b6b"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "0bd68bef46fbb0701293d65819af454fce344e7205e00071f0d1f5df74ed6217"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv7l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "4052f93242055ed1c0b8b4642c36b563b8abbbb2"
llvm_version = "18"
os = "macos"

    [[libclangex.download]]
    sha256 = "978951e3afff36d99a884d9c61d90e2a2c90d3f38e5ddc2f3b842a20293e6a5a"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-apple-darwin-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
git-tree-sha1 = "b564bbf43455f734b5442c1cacef406147e4c5ea"
llvm_version = "18"
os = "macos"

    [[libclangex.download]]
    sha256 = "d898b4b822c4b7a0055f8e67d969b55969525a3f2bfb27e94bb73474e0d1e60e"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.aarch64-apple-darwin-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "e66c23e06e75253d52a5912a951df9b505e9d401"
llvm_version = "18"
os = "freebsd"

    [[libclangex.download]]
    sha256 = "87747d009ece4aafeb897c3258df153ed669f6156ca6dffcc9efc8604102b344"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-unknown-freebsd-llvm_version+18.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0a96a5d9a4f0db30b8ee6f6d078dd2ec01445b5"
llvm_version = "18"
os = "windows"

    [[libclangex.download]]
    sha256 = "3999fb740e74e83b51d56bc7e40627ffeb78c22888e67b5bb20943305b0e2064"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.i686-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59014134335658d268ca7f64f3692bf11dbb29bf"
llvm_version = "18"
os = "windows"

    [[libclangex.download]]
    sha256 = "45a15d66c6b0653eb4d2169e78037c52c1bbc59c8896aa3fca80f9e453fcbbeb"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1df1b5461ad9679155d3514c557e14e2774abe39"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "9dbb09bcce983bfdfbff88c20971abd1884f0283ebfef9543ce16c1678cee04b"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.i686-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e92798d3c512b803030998aefb609b57cfcb8c23"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "e6571bf1cb848f641444914b89b38e4346287d27bc54b06948fe647ee99a2f2f"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c6a25ff17ffe6587566ab069530467e09ff98e8"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "a563dd13a4ccf23bece8f14c4a31ff58132b29b56490994c3b71a8099300ddd5"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.aarch64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a833e66f0be2c79fe69597b2627ba873266ffda4"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "756d2083cd10bf457855aa13bd56d8305ead93170d94d236a27afb3706e8ffdd"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv6l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbcc003acb1553cc35dbcfcedf49520a655ce680"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "8dc5e074ad7b27eabbb765b197bfd31bcda2f3b2ff147e5291914966b2ff3c92"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv7l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57e530d4420ab3cbc4ce7deb1976f266b608f925"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "66b76eba232dded6f32d6d0afafee51a84088b519e4b0b24009db0d8fa5685c3"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.powerpc64le-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c615d5eb1bfc595fd1185282c196ba6ed139393f"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "960310afb0152b78f18b165cbe0c09f2d569b0008a08de7cac05467109feca57"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40719206ea8f50f06e8a0202ee947967305f5579"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "79026b2ffa14fd00cd3eaa90c0487205ee3625c864522b3d5405283853962156"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.aarch64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ead2538853b7919c749a0d69d1d1c9543ca8a9c5"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "ed344c4d897a9aa9af94758b79da9a204eec8078819964e7f105aa63d193a017"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv6l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbfddd566ee8ade921b187060869ea2533da7aa1"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "5e6b2c269f51de5a71e73729f926a29ced443b4defe4f7d59f683292e80f6637"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.armv7l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "a1f9cc17796560f2920242105a31951b26cad448"
llvm_version = "18.asserts"
os = "macos"

    [[libclangex.download]]
    sha256 = "3dafbbf6ab7b708d882e52bba8b6b537da55788fe961c2c1f7e14df1c2992a88"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
git-tree-sha1 = "bffc14c303c2731338a40a4429c1c35495b0eb9b"
llvm_version = "18.asserts"
os = "macos"

    [[libclangex.download]]
    sha256 = "ebf6527f56e5f8194d39054612d2949fbf057507688f1716256c101b7eef080e"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.aarch64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "92c0f3293390a1beebd028552642036449ce7ebf"
llvm_version = "18.asserts"
os = "freebsd"

    [[libclangex.download]]
    sha256 = "b97084a239f1fe5811593f9620996e6dc097ff0a4c141849e995c471fe9df7b1"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-unknown-freebsd-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52d415974cb2970ed04ecd85a6c6afa97552efd4"
llvm_version = "18.asserts"
os = "windows"

    [[libclangex.download]]
    sha256 = "3f463f81030d66f0ccd9ce6c7044dfa83c42a69b7f05db3087bf9ba3a564dea3"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.i686-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "585bfed3ee7498427e571df37441d9578dfabe89"
llvm_version = "18.asserts"
os = "windows"

    [[libclangex.download]]
    sha256 = "02dd8c5f083789c2a92d4cff9b232d4da47a9f81c54612a166005f700fa8f221"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.1+0/libclangex.v0.4.1.x86_64-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
