[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb4301c3ff491438e32f57d2158a8b76ee2b33ff"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "75a37db52f144a8d4bcd0ec92a1ccd24089d615706ce7ce258d416428a413f1a"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.i686-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b1ef4df9c597aa733de317b0f7daea6a83c44a3"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "0923fd34ed73b18fd0a0e3c63321e458592ee208548f5e984390e4cce32016bb"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18a8180b652a889d226b71860718d7e6373fc432"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "5df9bea06868d70019ff04d0cddf5891411f159290963f9a6509a5fbd8f1a0f8"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.aarch64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84fcd7675250308694791356a5912bce243fc14"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "270dc48feaf891a0677d6d47334e05a9117712d9464bc97d1234a122bdf8d9c6"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv6l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8054ebdfbb7b4ad60286cf20e8699e8218e7f6ea"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "ef1fba364b0a289e9ffbe93a45c1c19ae63ec3cbc0dd0ec45b4b3cafebf0ba8c"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv7l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e579507509c21fb5c63d11e78588ddd450589ab7"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "14a6d412bf0cdc63791308dd4209132c30da708c1aed16a3d2d3ab48344a3b89"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.powerpc64le-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ecb32b166ddd2c0975f29c1d339b14f90970f63"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "9015b4d38d2daa182e4d97b758f0b9aafbe5a62da44b39fe4005bb3ed215fc0d"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bbfe69a43e66df61bf9ad68dd0456de8df3e5bb"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "eb25545d6e29a9ea21e66aab0021cf91550600c47525d459029c572e126efc5b"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.aarch64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3b978b6dcaf28f180991f3cb3f756abe66cc246"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "742c986c6a1995ba4a492b9bb6254fc30f1d21055c5bef2d8f32069d78f9adeb"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv6l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39dea26392176b2d166e20f3d17b55b3223a9da6"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "0222ff00b4b02d2d3bd7b2d139c3d38819abb028bd6b65c3b0f96707544583a2"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv7l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "42ee1860f3a0c0f7f0051c26afb44b77c0000016"
llvm_version = "18"
os = "macos"

    [[libclangex.download]]
    sha256 = "b1d3de13f6ba9d7619c59c1ac899309f1ed6b26aae014ca62f803b7f7dedd98e"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-apple-darwin-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
git-tree-sha1 = "b4cce73d411b0b4a0b4cc607bbddc1ddf3d67810"
llvm_version = "18"
os = "macos"

    [[libclangex.download]]
    sha256 = "21336219e4ba879ed018c8556b85860150a911a249684d76d9c7ffb81dc47f01"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.aarch64-apple-darwin-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "7245c412cc3d2c7bb90e20cbe32e9effe6a75ac0"
llvm_version = "18"
os = "freebsd"

    [[libclangex.download]]
    sha256 = "b60da3d99cb153c6c42344b0cb4908476219462b5bdcf66b304d1f771f74a14a"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-unknown-freebsd-llvm_version+18.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdaa82d639617ec5f71ec63f685f5bb5def00187"
llvm_version = "18"
os = "windows"

    [[libclangex.download]]
    sha256 = "bc4e1608eb74d59f69d6a18100327ebf7935a5e55ebe9384b0e0c4e8172652d3"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.i686-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d193e93444498c6282c476f32e29c341c2b42fca"
llvm_version = "18"
os = "windows"

    [[libclangex.download]]
    sha256 = "a420a6974a530f49693dbf1aa879714565e61446190626b26a758e407b89defb"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11a1732d841c1e0cc89b11a0a39d4a2498be5d06"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "f9cc19f3ae1e6ed107f98704f6ab77ff543fc49801425336c603c810b84a272a"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.i686-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f95b1139eb49c23210533b33aedb4c13c772f33"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "54f55e591b6b8429f71b12f771ec6e67250c3c3c4a1dcc396217fba6da353f7d"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cb8412f13bae1b021bebdac7a35951ad517d53"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "28d97fa74fbaa0c881657774f243c0c181ca8976fe467460e91bf9ed6a681d9e"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.aarch64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d433f5d7d8a7ed6c5c75734928a7fc8efa248e09"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "8bb5ba72252b574e1c144b53f38b91f744a4305fc0283f83cf797ab7e29042a2"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv6l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca4acc073df8c9122dec1d1c79addc54de827642"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "7e0c85d071f8fb4831b05bbb2ed5bd7bc902d34800aafa5553a4bb0ac0e64194"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv7l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "144a8de3b117dbc416cdb3d8780bb6a37632f93b"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "48d5f83bba95130934df6fc4d09c3d7c3d7dd6c8a0c3bcfcf005007407b817ed"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.powerpc64le-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fb1a97669252f12266502de75b293b10954e8cf"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "f5f0c41e13eddde4707f9fbb70523239f7494ff1ce258459d4ff4ef6e3103615"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "248fba23dba109cbe62bf62b1e2e106466fe38cb"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "1f340ce4e182cc181ad303e5115bcf411e2a03aa5126c0edc048d02fd8d4a56c"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.aarch64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26372ca81971cef809157128d6c72def83977a60"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "bd411b1af9def55a40f7fc366730e8c0a7e5d529b3318a9002d78909e743ca5f"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv6l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20c3b9d38195238944b6012c486b94942859178f"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "8b084d100490f556781e6a4e685a7ab757be9fe1f6982e2f7cbb02009921ca23"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.armv7l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "0b5adaae9135174b4b0c180b1ae0cbe153b573f0"
llvm_version = "18.asserts"
os = "macos"

    [[libclangex.download]]
    sha256 = "c6c67f43d367444e30b5f33ce05ccca63cbf4ff5ab7af564cce5b7d30277c5f4"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
git-tree-sha1 = "34418dce0310b1c1a8731633afae00f219fc3e3a"
llvm_version = "18.asserts"
os = "macos"

    [[libclangex.download]]
    sha256 = "a89386564f7aec8786b4d83223b17e6970dafcd810f2a36538978b5893fb1a56"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.aarch64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "8b22dd8a7011e64a675f0fd4642fc65967475b6c"
llvm_version = "18.asserts"
os = "freebsd"

    [[libclangex.download]]
    sha256 = "ce770afed020b71d6f9bfcecdf8628d6c63ef56bddfce08cb80ea3a0f6eeab2f"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-unknown-freebsd-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba1b9929bf532b25a18441681b0e90dd7b8c992c"
llvm_version = "18.asserts"
os = "windows"

    [[libclangex.download]]
    sha256 = "738e80935b7addd1e76e891d81756d22358ef498baf106d07279fbd4139122f4"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.i686-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1748e26e08ff2e64a3a465e80196ad055ba22812"
llvm_version = "18.asserts"
os = "windows"

    [[libclangex.download]]
    sha256 = "a67399fa786a017ef075b633362fca12c8c8a250f1b5cae0b16100e075176a33"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.2+0/libclangex.v0.4.2.x86_64-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
