[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a01221907ce08f67b754e464e18a412969eb28bf"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "7f50417489edfc8954c9dafe295b0ee54ca499d25af91bc71459aab2b58a8b11"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.i686-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c5c627441c3fc073c89633d4647b99066efb741"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "42a4b0f7a0493a49476fd5dcc96f013f8afe6d507e6114a27a79cb3a0cbdd01c"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70f6d70823f31bb46abf936dc2e795dfd17d22ef"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "2d67e6a3fd308a8d8ab289778c9fadbcf473752d0b3e68d4acbb2c68ea085eae"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.aarch64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06eb1feba55123321d747b608bc836058fea8dcb"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "5d59cc5f1c80537417bb356d6a7f1a5869dc9fbbb3943b6ed67beb7c9e6c5d4e"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv6l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d29f872c58fe4688ec9dfe8cd92be0cfa7289010"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "2e662608f5552889a504b7e520f03b78f89420932e3c515a74bbf9c47fc5e4f4"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv7l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c887b37c01ddc464be1a0ffdbd7fd37158f9bca"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "1825b1e3a728eb924e883697b75124092e6f3417cce2e8c92feb34ac43a20878"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.powerpc64le-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8af26088eae4e4c6308578c403a790b4c832458f"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "1a467a4ee799d16f29c3cae1a9a75cc8d71ce0b1cc333762a7bc2697dee82de7"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f59d9adb98bd0b767d4d52438d2c585db8121488"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "0ab33f7a04c4906abbd90984659dcec34b792ef69abf6c2fa5cb8cff4d54daf7"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.aarch64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e265f93ae196ba4925e172c6ed24158cac1e58f7"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "eaa4a8e17d51b5edb6fc5284a1e58f740a34b61deb423d9f833daf104f50fd68"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv6l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd99e5c1f16eae1c15fd5a13c6cc0ac142fa04e0"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libclangex.download]]
    sha256 = "4de1823ded42e249bf4057796eb6a79e992d187f58a88f34fbbaa692f30affd5"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv7l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "509e2d73236b689a27a841a513c2f8ce388fb486"
llvm_version = "18"
os = "macos"

    [[libclangex.download]]
    sha256 = "88ccb792c74a777a07013a1a6cb19e9f274d51cc2613691311cec9432930db82"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-apple-darwin-llvm_version+18.tar.gz"
[[libclangex]]
arch = "aarch64"
git-tree-sha1 = "fc7495f5a1c53b402e608b0352f7b9b37fd82f24"
llvm_version = "18"
os = "macos"

    [[libclangex.download]]
    sha256 = "8ed2e9a106206b765ba146c2722aeae79cd845fc37b8e4d4e2ae8b547abf53d3"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.aarch64-apple-darwin-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "df70428d89afe9d2a515d88ff52b6145fa662bde"
llvm_version = "18"
os = "freebsd"

    [[libclangex.download]]
    sha256 = "1e4769a8f59881b2511fd6b5f3becbfa90a6c01bb7976460439fe562a77a6074"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-unknown-freebsd-llvm_version+18.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61df91439ddd4b4faabc163ad78f33cf7341e9ed"
llvm_version = "18"
os = "windows"

    [[libclangex.download]]
    sha256 = "9573005ad0e94c40a012bd994e396f2a41ed9713a87142b753721ab519403a8a"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.i686-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12be1a97f347999c1bbdc6be970444c02daeea6d"
llvm_version = "18"
os = "windows"

    [[libclangex.download]]
    sha256 = "83bb22d0b55839f02cec140c1efd678fdc72f3e1785b4e41f66184571416eaaf"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50f6c27a891cedb9435a00da189c31c4cd94c723"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "7684bf052c851fc37b5f8813650ce59e1c236105cc1967df3849d8c44deaef77"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.i686-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6f105fdd316c817b39a2dcde2801e651af79f79"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "9bfad503d5e53560e7b408050fbecbb4526f148ff36116f3d0ac548105bceb9f"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e637c152f52d7a1994f19dfc5b302748e4ed97e"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "7d3f0361ec366f4039cb5cee08723bcc1c2a7744a95c98d819376dc1a1e82859"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.aarch64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3efc0c1faf439a902db4d566a3a66cfc3048d7e"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "fc8f9f50f8234383c3b06a1dc13c22dc267504d798a0f83b15bb59ac5fba47db"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv6l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "229344663d63ce328f98bfcf23c8545d3fefb7b8"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "d8917d539f16ff3b57b42373e2ef536d173082cb194ce6b4c94bb6ccbfef5022"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv7l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b7deb1704cea664438068f8fe471b062540ebcd"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "16d4bb0fd996440a64fa9f4bbc9614cfdf3d958064a8a2a2607f5648edda76fa"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.powerpc64le-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90fe00e7425185dd52fb533be7ce048506e86108"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "1219c1faabc36a7bd6acbb20b2cea1f716da0965e5da0919608d481c4d41ba63"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2672b074022786fcc4aad921b717ffd6fdbafdc"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "38df9ef1c50e27e198ae50eb63a7fcd56df8aafd3f86155ab92179f8e25edbf3"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.aarch64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8584c29b05d887d91508dda394677ee6a5589b16"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "13d4b3c4ddb338e6d6b12be29e59d4e63e5824b189879a0e44ecf8ab4eead8a2"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv6l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df7d1182e043301d542d441914ec9f078fcce9eb"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libclangex.download]]
    sha256 = "5bf568e0515bfcb447ecc6b942f15ad0f10e6d29e8d24fea9951c39e3edf01fe"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.armv7l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "c80bdbf8b6aea33ec61e12af76786a2f15b6baee"
llvm_version = "18.asserts"
os = "macos"

    [[libclangex.download]]
    sha256 = "a9af0190042e318283685a134c8e35e196a35fba162cf57830de0f5d7155edf5"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "aarch64"
git-tree-sha1 = "fb7960b3a6d590a028ca50bf646e7285d97787ca"
llvm_version = "18.asserts"
os = "macos"

    [[libclangex.download]]
    sha256 = "875c89e56be1a6db4ebdc401ff4c420804e47b5e81e64f198321750b0cada8bc"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.aarch64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
git-tree-sha1 = "c86a09d0b0150aab800c10388f2eb5e1863a188d"
llvm_version = "18.asserts"
os = "freebsd"

    [[libclangex.download]]
    sha256 = "da91e105be0d8c75946d7e20c9f2f65a3d075a352f9628ae2aef41e0adaa48ea"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-unknown-freebsd-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2c6e8519ecfb49267d98e8fff99300a1bb6c822"
llvm_version = "18.asserts"
os = "windows"

    [[libclangex.download]]
    sha256 = "f0f2fa390a315153accf9ea97407dd37794a28cf99b3502a3fdb56845e2fa9f2"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.i686-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
[[libclangex]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d41612ee64464558ad94c55d82040d3480c2956a"
llvm_version = "18.asserts"
os = "windows"

    [[libclangex.download]]
    sha256 = "a53142f04a021ba77200133b57b55ac8053d8cc7c90ea4798a00b6086dc3d48f"
    url = "https://github.com/JuliaBinaryWrappers/libclangex_jll.jl/releases/download/libclangex-v0.4.0+0/libclangex.v0.4.0.x86_64-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
